/**
 * Multi-locale corpus editions: family grouping + preferred language pick.
 * Pure functions — no Angular DI, safe for node tests.
 */

/** Known content locale suffixes in document ids. */
export const KNOWN_LOCALE_SUFFIXES = [
  'es',
  'en',
  'zh',
  'hi',
  'ar',
  'la',
  'it',
  'fr',
  'de',
  'pt',
  'el',
] as const;

export type KnownLocale = (typeof KNOWN_LOCALE_SUFFIXES)[number];

/** UI app languages (reader chrome / i18n surface). */
export const APP_UI_LOCALES = ['es', 'en', 'zh', 'hi', 'ar'] as const;
export type AppUiLocale = (typeof APP_UI_LOCALES)[number];

/** Content locales including Latin and other corpus packs. */
export const CONTENT_LOCALES = [
  'es',
  'en',
  'zh',
  'hi',
  'ar',
  'la',
  'it',
  'fr',
  'de',
  'pt',
  'el',
] as const;
export type ContentLocale = (typeof CONTENT_LOCALES)[number];

/** Minimal meta shape used by grouping (matches DocumentMeta fields we need). */
export interface LocaleMeta {
  id: string;
  locale?: string;
  title?: string;
  shortTitle?: string;
  unitCount?: number;
  kind?: string;
  sourceUrl?: string;
  sourceNote?: string;
  /** Provenance of this pack's text when known. */
  translationProvenance?: 'official' | 'ai';
  author?: string;
  compiler?: string;
  bodyPath?: string;
  indexPath?: string;
}

export interface DocumentFamily<T extends LocaleMeta = LocaleMeta> {
  /** Stable base id without locale suffix (e.g. `nicea-i`, `cceo`). */
  key: string;
  editions: T[];
  /** Edition for the given preferred locale (after fallback). */
  preferred: T;
}

/** Pref value: concrete locale or follow device/browser. */
export type ContentLocalePref = 'system' | string;

/** Prefer order: es, en, zh, hi, ar, la, then other European. */
const LOCALE_ORDER = [
  'es',
  'en',
  'zh',
  'hi',
  'ar',
  'la',
  'it',
  'fr',
  'de',
  'pt',
  'el',
];

const SUFFIX_RE = new RegExp(
  `-(${KNOWN_LOCALE_SUFFIXES.join('|')})$`,
  'i',
);

const AI_ID_SUFFIX_RE = /-ai$/i;

const AI_SOURCE_NOTE_RE =
  /generada por IA|generated by AI|AI[- ]generated|AI translation|traducci[oó]n.*IA|machine[- ]translated|人工智能|人工智慧/i;

/** Strip trailing `-ai` sibling marker from a pack id. */
function stripAiSuffix(id: string): string {
  return id.replace(AI_ID_SUFFIX_RE, '');
}

/**
 * Family key for a document pack id.
 * `nicea-i-es` + locale es → `nicea-i`
 * `constantinopla-i-la` → `constantinopla-i`
 * `cic-es` → `cic`
 * `lg-en` → `lg`
 * `lg-en-ai` → `lg` (AI sibling of en edition)
 * `cceo-es-ai` → `cceo`
 * `bible-pueblo-de-dios-es` → `bible-pueblo-de-dios`
 * Unknown suffix / no locale → id as-is (singleton family).
 */
export function familyKey(id: string, locale?: string | null): string {
  if (!id) return '';
  // Strip AI sibling marker first so `lg-en-ai` → family `lg`
  const base = stripAiSuffix(id);
  const loc = (locale || '').toLowerCase().trim();
  if (loc && base.toLowerCase().endsWith(`-${loc}`)) {
    return base.slice(0, -(loc.length + 1));
  }
  const m = base.match(SUFFIX_RE);
  if (m) {
    return base.slice(0, -m[0].length);
  }
  return base;
}

/** Normalize BCP-47 / browser language to a short corpus locale (`es-MX` → `es`). */
export function normalizeLocaleCode(code?: string | null): string {
  if (!code) return '';
  const primary = code.trim().toLowerCase().split(/[-_]/)[0] || '';
  return primary;
}

/**
 * Resolve the effective content locale from prefs + environment.
 * @param pref `system` | concrete code
 * @param navigatorLanguage e.g. `navigator.language` (injectable for tests)
 * @param fallback default when system has no usable primary (`es`)
 */
export function resolveContentLocale(
  pref: ContentLocalePref | undefined | null,
  navigatorLanguage?: string | null,
  fallback = 'es',
): string {
  if (pref && pref !== 'system') {
    const n = normalizeLocaleCode(pref);
    if (n) return n;
  }
  const fromNav = normalizeLocaleCode(navigatorLanguage);
  if (fromNav) return fromNav;
  return fallback;
}

function localeOf(meta: LocaleMeta): string {
  if (meta.locale) return normalizeLocaleCode(meta.locale);
  const base = stripAiSuffix(meta.id);
  const m = base.match(SUFFIX_RE);
  return m ? m[1].toLowerCase() : '';
}

function editionSortKey(meta: LocaleMeta): string {
  const loc = localeOf(meta);
  const idx = LOCALE_ORDER.indexOf(loc);
  const rank = idx >= 0 ? idx : 99;
  // Prefer official over AI when same locale
  const aiRank = isAiEdition(meta) ? 1 : 0;
  return `${String(rank).padStart(2, '0')}:${loc}:${aiRank}:${meta.id}`;
}

/**
 * True if this pack is an AI translation sibling.
 * Detected via id `-ai` suffix, `translationProvenance`, or sourceNote keywords.
 */
export function isAiEdition(meta: LocaleMeta): boolean {
  if (meta.id && AI_ID_SUFFIX_RE.test(meta.id)) return true;
  if (meta.translationProvenance === 'ai') return true;
  if (meta.sourceNote && AI_SOURCE_NOTE_RE.test(meta.sourceNote)) return true;
  if (meta.translationProvenance === 'official') return false;
  return false;
}

/**
 * Short provenance badge for chips / chrome.
 * Non-AI: ES, EN, 中文, हिन्दी, عربية, LA…
 * AI: ES(IA), EN(AI), 中文(AI), हिन्दी(AI), عربية(AI)…
 * Spanish uses IA; other locales use AI (or native-script language name + AI).
 */
export function localeProvenanceBadge(
  locale?: string | null,
  isAi?: boolean,
): string {
  const code = normalizeLocaleCode(locale);
  if (!code) return isAi ? '?(AI)' : '?';
  const native: Record<string, string> = {
    es: 'ES',
    en: 'EN',
    zh: '中文',
    hi: 'हिन्दी',
    ar: 'عربية',
    la: 'LA',
    it: 'IT',
    fr: 'FR',
    de: 'DE',
    pt: 'PT',
    el: 'EL',
  };
  const label = native[code] || code.toUpperCase();
  if (!isAi) return label;
  if (code === 'es') return 'ES(IA)';
  return `${label}(AI)`;
}

/**
 * Multi-language disclaimer for AI translation packs.
 * States AI origin, not official Holy See, for study; official/Latin prevails.
 */
export function aiSourceNote(
  targetLocale: string,
  sourceTitle: string,
  sourceId: string,
  sourceLangLabel: string,
): string {
  const loc = normalizeLocaleCode(targetLocale);
  const src = `${sourceTitle} (${sourceId}, ${sourceLangLabel})`;
  const templates: Record<string, string> = {
    es: `Traducción generada por IA a partir de «${sourceTitle}» (${sourceId}, ${sourceLangLabel}). No es una traducción oficial de la Santa Sede. Solo para estudio; prevalece el texto oficial o latino.`,
    en: `AI-generated translation from "${sourceTitle}" (${sourceId}, ${sourceLangLabel}). Not an official Holy See translation. For study only; the official or Latin text prevails.`,
    zh: `由人工智能根据「${sourceTitle}」（${sourceId}，${sourceLangLabel}）生成的翻译。非教廷官方译本。仅供学习使用；以官方或拉丁文本为准。`,
    hi: `${src} से AI-जनित अनुवाद। यह Holy See (पवित्र सी) का आधिकारिक अनुवाद नहीं है। केवल अध्ययन के लिए; आधिकारिक या लैटिन पाठ मान्य है।`,
    ar: `ترجمة مولّدة بالذكاء الاصطناعي من «${sourceTitle}» (${sourceId}، ${sourceLangLabel}). ليست ترجمة رسمية للكرسي الرسولي. للدراسة فقط؛ يسود النص الرسمي أو اللاتيني.`,
  };
  return templates[loc] || templates['en'];
}

/**
 * Pick the best edition for the user's preferred content locale.
 * 1) exact locale match (prefer non-AI when both exist)
 * 2) Spanish (corpus default)
 * 3) stable order (es, en, zh, … then id)
 */
export function pickPreferredEdition<T extends LocaleMeta>(
  editions: T[],
  preferredLocale: string,
): T {
  if (!editions.length) {
    throw new Error('pickPreferredEdition: empty editions');
  }
  if (editions.length === 1) return editions[0];
  const pref = normalizeLocaleCode(preferredLocale);
  const exact = editions.filter((e) => localeOf(e) === pref);
  if (exact.length) {
    const official = exact.find((e) => !isAiEdition(e));
    return official || exact[0];
  }
  const es = editions.filter((e) => localeOf(e) === 'es');
  if (es.length) {
    const official = es.find((e) => !isAiEdition(e));
    return official || es[0];
  }
  const sorted = [...editions].sort((a, b) =>
    editionSortKey(a).localeCompare(editionSortKey(b)),
  );
  return sorted[0];
}

/** Group corpus metas into multi-locale families; attach preferred edition. */
export function groupByFamily<T extends LocaleMeta>(
  metas: T[],
  preferredLocale: string,
): DocumentFamily<T>[] {
  const map = new Map<string, T[]>();
  for (const m of metas) {
    const key = familyKey(m.id, m.locale);
    const list = map.get(key);
    if (list) list.push(m);
    else map.set(key, [m]);
  }
  const families: DocumentFamily<T>[] = [];
  for (const [key, editions] of map) {
    const sorted = [...editions].sort((a, b) =>
      editionSortKey(a).localeCompare(editionSortKey(b)),
    );
    families.push({
      key,
      editions: sorted,
      preferred: pickPreferredEdition(sorted, preferredLocale),
    });
  }
  // Stable catalog order: by preferred title then id
  families.sort((a, b) => {
    const ta = (a.preferred.title || a.preferred.id).toLowerCase();
    const tb = (b.preferred.title || b.preferred.id).toLowerCase();
    const c = ta.localeCompare(tb, 'es');
    return c !== 0 ? c : a.key.localeCompare(b.key);
  });
  return families;
}

/** Collapse metas to one preferred edition per family (catalog listing). */
export function listPreferredEditions<T extends LocaleMeta>(
  metas: T[],
  preferredLocale: string,
): T[] {
  return groupByFamily(metas, preferredLocale).map((f) => f.preferred);
}

/**
 * One edition per family+locale, official over AI.
 * Used when the search universe spans every language.
 */
function collapseOfficialOverAiPerLocale<T extends LocaleMeta>(
  metas: readonly T[],
): T[] {
  const map = new Map<string, T[]>();
  for (const m of metas) {
    const key = `${familyKey(m.id, m.locale)}::${localeOf(m)}`;
    const list = map.get(key);
    if (list) list.push(m);
    else map.set(key, [m]);
  }
  const out: T[] = [];
  for (const eds of map.values()) {
    out.push(
      pickPreferredEdition(eds, localeOf(eds[0]) || eds[0].locale || ''),
    );
  }
  return out;
}

/**
 * Default search universe for a resolved content locale.
 * One edition per family in that locale (official over AI).
 * `allLocales`: every language, still dropping AI siblings of an official pack.
 */
export function listSearchUniverse<T extends LocaleMeta>(
  metas: readonly T[],
  preferredLocale: string,
  allLocales = false,
): T[] {
  if (!metas?.length) return [];
  if (allLocales) return collapseOfficialOverAiPerLocale(metas);
  const loc = normalizeLocaleCode(preferredLocale);
  if (!loc) return collapseOfficialOverAiPerLocale(metas);
  const scoped = metas.filter((m) => localeOf(m) === loc);
  return listPreferredEditions(scoped, loc);
}

/** All editions sharing a family with `documentId` (including itself). */
export function editionsForDocument<T extends LocaleMeta>(
  metas: T[],
  documentId: string,
): T[] {
  const self = metas.find((m) => m.id === documentId);
  const key = familyKey(documentId, self?.locale);
  return metas
    .filter((m) => familyKey(m.id, m.locale) === key)
    .sort((a, b) => editionSortKey(a).localeCompare(editionSortKey(b)));
}

/** Human label for corpus locale codes (shared with CorpusService). */
export function localeLabel(locale?: string | null): string {
  if (!locale) return 'Idioma';
  const code = normalizeLocaleCode(locale);
  const map: Record<string, string> = {
    es: 'Español',
    en: 'English',
    zh: '中文',
    hi: 'हिन्दी',
    ar: 'العربية',
    la: 'Latina',
    it: 'Italiano',
    fr: 'Français',
    de: 'Deutsch',
    pt: 'Português',
    el: 'Ελληνικά',
  };
  return map[code] || locale.toUpperCase();
}

/**
 * Short badge (ES, LA) for chips / lector chrome.
 * Pass `isAi` (or a meta via callers) to get provenance-aware badges.
 */
export function localeBadge(
  locale?: string | null,
  isAi?: boolean,
): string {
  if (isAi) return localeProvenanceBadge(locale, true);
  if (!locale) return '?';
  return normalizeLocaleCode(locale).toUpperCase() || '?';
}

/**
 * Unit index to open when switching language.
 * Same unitIndex only when both packs report equal unitCount; else 0.
 */
export function mapUnitIndexOnLocaleSwitch(
  fromUnitIndex: number,
  fromUnitCount?: number | null,
  toUnitCount?: number | null,
): number {
  const idx = Math.max(0, Math.floor(fromUnitIndex) || 0);
  if (
    typeof fromUnitCount === 'number' &&
    typeof toUnitCount === 'number' &&
    fromUnitCount > 0 &&
    fromUnitCount === toUnitCount &&
    idx < toUnitCount
  ) {
    return idx;
  }
  return 0;
}

/** Subtitle for catalog when multiple editions exist. */
export function multiLocaleSubtitle(editions: LocaleMeta[]): string | null {
  if (editions.length < 2) return null;
  const labels = editions.map((e) => {
    const loc = localeOf(e) || e.locale;
    if (isAiEdition(e)) {
      return localeProvenanceBadge(loc, true);
    }
    return localeLabel(loc);
  });
  // Unique preserve order
  const seen = new Set<string>();
  const uniq: string[] = [];
  for (const l of labels) {
    if (!seen.has(l)) {
      seen.add(l);
      uniq.push(l);
    }
  }
  if (uniq.length < 2) return null;
  return `${uniq.join(' · ')}`;
}
