#!/usr/bin/env bash
# Capacitor production web → sync → signed bundleRelease (.aab) → monorepo dist/
# Secrets (never commit): DV_KEYSTORE_PATH, DV_KEYSTORE_PASSWORD, DV_KEY_ALIAS, DV_KEY_PASSWORD
# Optional: DV_PACKAGE_NAME override of applicationId; DV_PACKAGE_LOG for tee.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND="$ROOT/frontend"
ANDROID="$FRONTEND/android"
OUT_AAB="$ROOT/dist/documentos-vaticanos-release.aab"
VERSION_JS="$ROOT/scripts/android-version.js"

run() {
  if [[ -n "${DV_PACKAGE_LOG:-}" ]]; then
    "$@" 2>&1 | tee -a "$DV_PACKAGE_LOG"
    return "${PIPESTATUS[0]}"
  else
    "$@"
  fi
}

# --- version from monorepo package.json ---
VERSION_JSON=$(node "$VERSION_JS" "$(node -p "require('$ROOT/package.json').version")")
VERSION_NAME=$(node -p "JSON.parse(process.argv[1]).versionName" "$VERSION_JSON")
VERSION_CODE=$(node -p "JSON.parse(process.argv[1]).versionCode" "$VERSION_JSON")
echo "==> Android versionName=$VERSION_NAME versionCode=$VERSION_CODE"

# --- signing secrets ---
KEYSTORE_PATH="${DV_KEYSTORE_PATH:-${HOME}/.config/documentos-vaticanos/docvat-upload.jks}"
KEYSTORE_PASSWORD="${DV_KEYSTORE_PASSWORD:-}"
KEY_ALIAS="${DV_KEY_ALIAS:-docvat-upload}"
KEY_PASSWORD="${DV_KEY_PASSWORD:-${KEYSTORE_PASSWORD}}"

if [[ ! -f "$KEYSTORE_PATH" ]]; then
  echo "ERROR: release keystore not found at $KEYSTORE_PATH" >&2
  echo "HINT: set DV_KEYSTORE_PATH / create upload keystore outside git (see deploy/PLAY-CLOSED-TESTING.md)" >&2
  exit 1
fi
if [[ -z "$KEYSTORE_PASSWORD" ]]; then
  echo "ERROR: DV_KEYSTORE_PASSWORD is required for signed AAB" >&2
  exit 1
fi

# Play idle job clones the repo without the full CI yarn install. npm run build
# shells out to `ng`; without frontend/node_modules that is `ng: not found` (127).
ensure_frontend_deps() {
  if [[ -x "$FRONTEND/node_modules/.bin/ng" ]]; then
    echo "==> frontend deps present ($FRONTEND/node_modules/.bin/ng)"
    return 0
  fi
  echo "==> installing frontend deps (ng missing — Play idle / clean checkout)"
  (
    cd "$FRONTEND"
    if command -v yarn >/dev/null 2>&1; then
      yarn install --production=false --prefer-offline || yarn install --production=false
    else
      npm install
    fi
  )
  if [[ ! -x "$FRONTEND/node_modules/.bin/ng" ]]; then
    echo "ERROR: @angular/cli still missing after install ($FRONTEND/node_modules/.bin/ng)" >&2
    exit 1
  fi
}
ensure_frontend_deps

cd "$FRONTEND"
echo "==> Production build + Capacitor sync (shared path with package-apk)"
if [[ ! -f dist/documentos-vaticanos/index.html ]]; then
  run npm run build
fi

CORPUS_DIST="$FRONTEND/dist/documentos-vaticanos/assets/corpus"
if [[ -f "$CORPUS_DIST/manifest.json" ]]; then
  echo "==> Corpus compress → $CORPUS_DIST"
  run node "$ROOT/scripts/corpus-compress.js" --root "$CORPUS_DIST"
fi

run npx cap sync android

CAP_BUILD_GRADLE="$ANDROID/app/capacitor.build.gradle"
if [[ ! -f "$CAP_BUILD_GRADLE" ]]; then
  if command -v git >/dev/null 2>&1 && git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "$ROOT" checkout -- frontend/android/app/capacitor.build.gradle 2>/dev/null || true
  fi
fi
if [[ ! -f "$CAP_BUILD_GRADLE" ]]; then
  cat >"$CAP_BUILD_GRADLE" <<'EOF'
// Generated by package-aab.sh
android {
  compileOptions {
      sourceCompatibility JavaVersion.VERSION_17
      targetCompatibility JavaVersion.VERSION_17
  }
}
dependencies {
}
if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}
EOF
fi
if [[ ! -d "$ANDROID/capacitor-cordova-android-plugins" ]]; then
  run npx cap sync android
fi
if [[ ! -f "$CAP_BUILD_GRADLE" ]]; then
  echo "ERROR: missing $CAP_BUILD_GRADLE" >&2
  exit 1
fi

PUBLIC_DIR="$ANDROID/app/src/main/assets/public"
if [[ ! -f "$PUBLIC_DIR/index.html" ]]; then
  echo "ERROR: Cap sync did not copy index.html to $PUBLIC_DIR" >&2
  exit 1
fi

if [[ ! -x "$ANDROID/gradlew" ]]; then
  echo "ERROR: missing $ANDROID/gradlew" >&2
  exit 1
fi

# --- Java home (same resolution as package-apk.sh) ---
resolve_java_home() {
  if [[ -n "${JAVA_HOME:-}" && -x "${JAVA_HOME}/bin/java" ]]; then
    echo "$JAVA_HOME"
    return 0
  fi
  local cand
  for cand in \
    /usr/lib/jvm/temurin-21-jdk-amd64 \
    /usr/lib/jvm/java-21-openjdk-amd64 \
    /usr/lib/jvm/java-17-openjdk-amd64 \
    /usr/lib/jvm/default-java; do
    if [[ -x "$cand/bin/java" ]]; then
      echo "$cand"
      return 0
    fi
  done
  if command -v java >/dev/null 2>&1; then
    local jbin
    jbin=$(readlink -f "$(command -v java)" 2>/dev/null || command -v java)
    echo "$(cd "$(dirname "$jbin")/.." && pwd)"
    return 0
  fi
  return 1
}

JAVA_RESOLVED="$(resolve_java_home || true)"
if [[ -z "$JAVA_RESOLVED" || ! -x "$JAVA_RESOLVED/bin/java" ]]; then
  echo "ERROR: could not resolve a usable JAVA_HOME" >&2
  exit 1
fi
export JAVA_HOME="$JAVA_RESOLVED"
export PATH="$JAVA_HOME/bin:$PATH"
echo "==> JAVA_HOME=$JAVA_HOME ($("$JAVA_HOME/bin/java" -version 2>&1 | head -1))"

GP="$ANDROID/gradle.properties"
if [[ -f "$GP" ]] && grep -qE '^[[:space:]]*org\.gradle\.java\.home=' "$GP"; then
  PINNED=$(grep -E '^[[:space:]]*org\.gradle\.java\.home=' "$GP" | head -1 | sed 's/.*=//')
  if [[ ! -x "${PINNED}/bin/java" ]]; then
    echo "==> Rewriting invalid org.gradle.java.home=$PINNED → $JAVA_HOME"
    sed -i '/^[[:space:]]*org\.gradle\.java\.home=/d' "$GP"
  fi
fi

is_android_sdk_root() {
  local d="$1"
  [[ -d "$d/platforms" || -d "$d/build-tools" || -f "$d/platform-tools/adb" ]]
}

if [[ -z "${ANDROID_HOME:-}${ANDROID_SDK_ROOT:-}" ]]; then
  for sdkcand in \
    "$FRONTEND/.android-build-tools/sdk" \
    "$FRONTEND/.android-build-tools" \
    "$FRONTEND/android-sdk" \
    "${HOME}/Android/Sdk" \
    /opt/android-sdk; do
    if [[ -d "$sdkcand" ]] && is_android_sdk_root "$sdkcand"; then
      export ANDROID_HOME="$sdkcand"
      export ANDROID_SDK_ROOT="$sdkcand"
      echo "==> ANDROID_HOME=$ANDROID_HOME"
      break
    fi
  done
fi
if [[ -n "${ANDROID_HOME:-}" && ! -d "${ANDROID_HOME}/platforms" && -d "${ANDROID_HOME}/sdk/platforms" ]]; then
  export ANDROID_HOME="${ANDROID_HOME}/sdk"
  export ANDROID_SDK_ROOT="$ANDROID_HOME"
fi
if [[ -n "${ANDROID_HOME:-}" && -d "$ANDROID_HOME" ]]; then
  echo "sdk.dir=$ANDROID_HOME" >"$ANDROID/local.properties"
fi

# Optional package name override (Console draft uses com.docvat)
if [[ -n "${DV_PACKAGE_NAME:-}" ]]; then
  echo "==> applicationId override DV_PACKAGE_NAME=$DV_PACKAGE_NAME"
fi

echo "==> Gradle bundleRelease (signed)"
cd "$ANDROID"
# Worker/bundletool for a ~GB corpus AAB needs more than the historic 1536m daemon heap.
export GRADLE_OPTS="${GRADLE_OPTS:-} -Xmx4096m"
# Pass signing + version via project properties (not written into VCS build.gradle secrets)
# --stacktrace: BundleToolRunnable otherwise hides the Caused-by (OOM on large corpus AAB).
GRADLE_ARGS=(
  bundleRelease
  --no-daemon
  --stacktrace
  "-PdvVersionCode=${VERSION_CODE}"
  "-PdvVersionName=${VERSION_NAME}"
  "-PdvStoreFile=${KEYSTORE_PATH}"
  "-PdvStorePassword=${KEYSTORE_PASSWORD}"
  "-PdvKeyAlias=${KEY_ALIAS}"
  "-PdvKeyPassword=${KEY_PASSWORD}"
)
if [[ -n "${DV_PACKAGE_NAME:-}" ]]; then
  GRADLE_ARGS+=("-PdvApplicationId=${DV_PACKAGE_NAME}")
fi
run ./gradlew "${GRADLE_ARGS[@]}"

AAB_SRC="$ANDROID/app/build/outputs/bundle/release/app-release.aab"
if [[ ! -f "$AAB_SRC" ]]; then
  # some AGP layouts
  AAB_SRC=$(find "$ANDROID/app/build/outputs/bundle" -name '*.aab' 2>/dev/null | head -1 || true)
fi
if [[ -z "${AAB_SRC:-}" || ! -f "$AAB_SRC" ]]; then
  echo "ERROR: AAB not produced under app/build/outputs/bundle" >&2
  exit 1
fi

mkdir -p "$ROOT/dist"
cp -f "$AAB_SRC" "$OUT_AAB"

SIZE=$(stat -c%s "$OUT_AAB" 2>/dev/null || stat -f%z "$OUT_AAB")
if [[ "$SIZE" -lt 100000 ]]; then
  echo "ERROR: AAB too small ($SIZE bytes)" >&2
  exit 1
fi

# ZIP structure check (AAB is a zip)
if command -v unzip >/dev/null 2>&1; then
  unzip -t "$OUT_AAB" >/dev/null
fi
if command -v file >/dev/null 2>&1; then
  file "$OUT_AAB"
fi

PACKAGE_NAME="${DV_PACKAGE_NAME:-}"
if [[ -z "$PACKAGE_NAME" ]]; then
  PACKAGE_NAME=$(grep -E 'applicationId\s+"' "$ANDROID/app/build.gradle" | head -1 | sed -E 's/.*applicationId[[:space:]]+"([^"]+)".*/\1/' || echo unknown)
fi

{
  echo "artifact=aab"
  echo "builtAt=$(date -Iseconds)"
  echo "source=$AAB_SRC"
  echo "path=$OUT_AAB"
  echo "bytes=$SIZE"
  echo "versionName=$VERSION_NAME"
  echo "versionCode=$VERSION_CODE"
  echo "packageName=$PACKAGE_NAME"
  echo "signed=true"
} >"$ROOT/dist/aab.meta.txt"

echo "OK aab: $OUT_AAB ($SIZE bytes) versionCode=$VERSION_CODE versionName=$VERSION_NAME package=$PACKAGE_NAME"
